### PR TITLE
Update to Scala 2.11.7 and SBT 0.13.9

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Hey @som-snytt, what are your plans here? What do you think about uploading it to a repository?

Btw, I'd love it if we could get regextractor into a shape ready for inclusion in scala/scala, what do you think?

**Comment by som-snytt** [comment]
@soc The important piece is that compiling a regex at runtime is unfortunate in general and to do it on every pattern match is a blocker. I haven't researched the alternatives yet.

**Comment by soc** [comment]
That's true! Given that the regex string is usually statically known, would it be possible to hoist the regex compilation out of the pattern match?

**Comment by som-snytt** [comment]
Yeah, that's the idea. I like the model of: if an independent library develops momentum, then consider enshrining it in the standard lib. As opposed to, let the std lib be a proving ground, with ongoing deprecations.

**Comment by som-snytt** [comment]
I promised an up-to-date release at some point, just for kicks. But closing the issue in light of:

https://github.com/blog/2124-kindly-closing-pull-requests

**Pull request closed without merging**
